version: '3'

volumes:
  caddy_root: {}
  caddy_etc: {}

services:
  caddy:
    restart: always
    image: wemakeservices/caddy-gen:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy_root:/root/.caddy
      - caddy_etc:/etc/caddy
    ports:
      - '80:80'
      - '443:443'

  index:
    restart: always
    image: nginx:latest
    labels:
      - 'virtual.host=sites.async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
    volumes:
      - ./sites.async.fi:/usr/share/nginx/html:ro

  www:
    restart: always
    image: jonikahara/www-async-fi:latest
    labels:
      - 'virtual.host=async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
      - 'virtual.port=80'

  clock:
    restart: always
    image: nginx:latest
    labels:
      - 'virtual.host=clock.async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
    volumes:
      - ./clock.async.fi:/usr/share/nginx/html:ro

  oh2ewl:
    restart: always
    image: nginx:latest
    labels:
      - 'virtual.host=oh2ewl.async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
    volumes:
      - ./oh2ewl.async.fi:/usr/share/nginx/html:ro

  uuid:
    restart: always
    image: gunicorn:latest
    build:
      context: ./gunicorn/
    labels:
      - 'virtual.host=uuid.async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
    volumes:
      - ./uuid.async.fi:/app:ro

  echo:
    restart: always
    image: gcr.io/google-containers/echoserver:1.8
    labels:
      - 'virtual.host=echo.async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
      - 'virtual.port=8080'

  past:
    restart: always
    image: nginx:latest
    labels:
      - 'virtual.host=past.async.fi'
      - 'virtual.tls-email=hostmaster@async.fi'
    volumes:
      - ./past.async.fi:/usr/share/nginx/html:ro
